# Generated by Django 4.1.13 on 2025-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesignup',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employeesignup',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employeesignup',
            name='password',
        ),
        migrations.AlterField(
            model_name='employeesignup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employeesignup',
            name='unique_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
